### ISSUE TITLE
highcharts требует платную лицензию

### ISSUE THREAD

**Issue by EKZERSIS** [discoveryjs/discovery#21]
Из-за этого невозможно использовать дискавери в коммерческих проектах.
Нужно добавить поддержку бесплатных графиков d3.js

**Comment by lahmatiy** [comment]
Thank you for the issue!
I strongly believe that including highcharts (or any other chart library) into the core of Discovery is not a good decision (since no options to not use it and vendor lock). There is a plan to extract "complex" views (a view that requires external dependencies) into separate packages (make them as plugins). I hope I can start work on it next week.

**Comment by lahmatiy** [comment]
Highcharts was removed in [1.0.0-beta.26](https://github.com/discoveryjs/discovery/releases/tag/v1.0.0-beta.26)
