### ISSUE TITLE
Pass data and context to queryHelpers

### ISSUE THREAD

**Issue by smelukov** [discoveryjs/discovery#74]
```js
addQueryHelpers({
  foo() {
    console.log(this.data);
    console.log(this.context);
  }
})
```

**Comment by lahmatiy** [comment]
Starting Discovery.js [1.0.0-beta.80](https://github.com/discoveryjs/discovery/releases/tag/v1.0.0-beta.80) (jora [1.0.0-beta.10](https://github.com/discoveryjs/jora/releases/tag/v1.0.0-beta.10)) custom methods are support for accessing to context via `this.context`. Custom methods can be a string (jora query) as well, and access to context via `#` as a regular queries.

Accessing to root data in methods via `this.data` is not supported. This limitation is due a custom method can be a string (jora query) and `@` (or `this.data`) refers to query root or the method itself instead of root query.
