### ISSUE TITLE
Could you please explain what I do wrong with built in tabs view?

### ISSUE THREAD

**Issue by FeltBoots** [discoveryjs/discovery#89]
I'm getting an error with this code snippet I took from tab.usage.js 
https://github.com/discoveryjs/discovery/blob/02798acce8e43f87a154bd23355a5d4222d440a3/src/views/tab.usage.js 

```
  const appTabs = utils.createElement('div', 'app-tabs-container')
  host.view.render(appTabs, {
    view: 'tabs',
    name: 'tabs',
    tabs: [
      {
        value: 'one',
        text: 'One'
      },
      {
        value: 'two',
        text: 'Two'
      },
      {
        value: 'three',
        text: 'Three'
      }
    ],
    content: {
      view: 'switch',
      content: [
        {
          when: '#.tabs="one"',
          content: 'text:"One"'
        },
        {
          when: '#.tabs="two"',
          content: 'text:"Two"'
        },
        {
          when: '#.tabs="three"',
          content: 'text:"Three"'
        }
      ]
    },
    beforeTabs: 'text:"<Content before tabs>"',
    afterTabs: 'text:"<Content after tabs>"'
  })
```

I am getting an error: `TypeError: Cannot use 'in' operator to search for 'tabs' in undefined`. I have no idea how to work with it. Trying follow examples from surrounding repos and docs in readme but it does not work for me.

**Comment by lahmatiy** [comment]
`host.view.render()` expected to have 4 arguments: `outputElement`, `config`, `data` and `context`. In your case you omitted last two arguments and therefore got an error. When a component works with `context` it expected that `context` is non-nullish. I'm not sure a fix for tabs is needed. Also, you should avoid using `host.view.render()` directly since it is intended for use in a component definition only.

**Comment by FeltBoots** [comment]
Thanks! I realised your point about `host.view.render()`. Now it works as expected.
